
# This script does the following in tn-seq  data processing
# 1. takes as an input an aggregate file from aerobio
# 2. merges it with the esential, cluster data 
# 3. rearranges output table in a nicer way 
# 4. saves it as a .csv file 
# 5. removes from the table non informative data (essential genes and genes without cluster assigned, genes with < N insertions)
# 6. creates a data.frame of genes where mutants completely dissapeared at time 2 
# 7. and another data.frame with the genes with fitness values and standard deviation data suitable for statistical comparisons 
# 8. and then both dataframes are saved as .csv files

# [input] inputfilename: Tn-Seq aggregate file (output of aerobio/magenta)
# [input] essentialsfile: .RData file that has a data table named "ALL_essentials". 
#         This contains gene essentiality data for 22 strains (generated by Federico Rosconi)
# [input] N: the minimum number of insertions in a gene. Genes with <N insertions will not 
#         be included in the statistical analysis.
# [input] outdirname: output directory name
process_single_expt <- function(inputfilename, essentialsfile, N, outdirname){
  source('./t.test2.R')
  library(ggplot2)
  
  #load necessary data
  All_essentials <- read.csv(essentialsfile, header=T, stringsAsFactors = F)
  aggfile <- read.csv(inputfilename, header=T, stringsAsFactors = F)
  filestub <- tools::file_path_sans_ext(basename(inputfilename))
  # if "Output" directory doesn't exist, create it 
  dir.create(outdirname, showWarnings = FALSE)
  
  # Make a new column for Total-Blank.Removed (this is the bottleneck-corrected total)
  aggfile$Blank.Removed <- as.numeric(aggfile$Blank.Removed)
  aggfile$Total.BN <- aggfile$Total - aggfile$Blank.Removed
  #merge aggregate data with essentiality
  tnfile <- merge(All_essentials, aggfile, by.x = "locus",by.y = "locus",all = F) 
  #reorder the columns 
  tnfile<-tnfile[,c(2:5,1,6:18,20,23,19,21,24:26, 29)]
  # write to file
  completefilename <- file.path(outdirname, paste0(filestub, '_complete.csv'))
  write.csv(tnfile, completefilename, row.names = F,quote=T)
  
  # remove essentials
  tnfile_sub<-subset(tnfile, Binomial.Call!="Essential") #5
  # remove rows where Total (bottleneck corrected) are <N or NA
  tnfile_sub <- tnfile_sub[!is.na(tnfile_sub$Total.BN) & tnfile_sub$Total.BN > N,]
  # separate genes that had no insertions at time2 (these have sd=X)
  tnfile_sub_nullW <- subset(tnfile_sub, sd=="X")
  tnfile_sub_W <- subset(tnfile_sub, sd!="X")
  # write these to file
  nullWfile <- file.path(outdirname, paste0(filestub, '_nullW.csv'))
  Wfile <- file.path(outdirname, paste0(filestub, '_W.csv'))
  if (nrow(tnfile_sub_nullW)>0){
    write.csv(tnfile_sub_nullW, nullWfile, row.names = F,quote=T)
  }
  write.csv(tnfile_sub_W, Wfile, row.names = F,quote=T)
  
  # perform an unpaired 2-sample t-test - comparing the observed W to the expected W
  # expected W is the median W of observed values. 
  tnfile_ttest <- tnfile_sub_W
  tnfile_ttest$W.expected <- median(tnfile_ttest$mean)
  tnfile_ttest$dW <- tnfile_ttest$mean - tnfile_ttest$W.expected
  tnfile_ttest$sd <- as.numeric(tnfile_ttest$sd)
  
  # retrieve t test p value
  tnfile_ttest$pvalue <- sapply(c(1:nrow(tnfile_ttest)), function(i){
    t <- t.test2(tnfile_ttest$mean[i], tnfile_ttest$W.expected[i], tnfile_ttest$sd[i], tnfile_ttest$sd[i], tnfile_ttest$Total.BN[i], tnfile_ttest$Total.BN[i])
    pval <- t[["p"]]
    return(pval)
  })
  
  #adjust p value for false discovery
  tnfile_ttest$padj <- p.adjust(tnfile_ttest$pvalue, "BH")
  # mark discoveries based on adjusted p value
  tnfile_ttest$Discovery <- ""
  tnfile_ttest$Discovery[tnfile_ttest$pvalue<=0.002]<-"***"
  tnfile_ttest$Discovery[tnfile_ttest$pvalue<=0.0002]<-"****"
  
  tnfile_ttest$Sig <- FALSE
  tnfile_ttest$Sig[tnfile_ttest$padj<=0.05] <- TRUE
  
  #write to file
  discoveriesfile <- file.path(outdirname, paste0(filestub, '_discovery.csv'))
  write.csv(tnfile_ttest, discoveriesfile, row.names = F,quote=T)
  
  #make a volcano plot
  tnfile_ttest$logp <- -log10(tnfile_ttest$padj)
  tnfile_ttest$Significant <- tnfile_ttest$padj<0.05 
  volcanoname <- file.path(outdirname, paste0(filestub, '_volcano.png'))
  ggplot(tnfile_ttest, aes(x=dW, y=logp, col=Significant))+geom_point()+theme_minimal()+
    geom_text(aes(label=ifelse(Significant,as.character(locus),'')),hjust=0,vjust=0)+
    scale_color_manual(values=c("black", "red"))
  ggsave(volcanoname, width=10, height=6)
}
